# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(10, 430, 150, 150))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("logo_ecci2.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.students_label = QtWidgets.QLabel(self.centralwidget)
        self.students_label.setGeometry(QtCore.QRect(160, 430, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.students_label.setFont(font)
        self.students_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.students_label.setObjectName("students_label")
        self.measurement_label = QtWidgets.QLabel(self.centralwidget)
        self.measurement_label.setGeometry(QtCore.QRect(20, 50, 280, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.measurement_label.setFont(font)
        self.measurement_label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.measurement_label.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.measurement_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.measurement_label.setObjectName("measurement_label")
        self.input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line.setGeometry(QtCore.QRect(210, 220, 91, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_line.setFont(font)
        self.input_line.setText("")
        self.input_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_line.setObjectName("input_line")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(60, 330, 200, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("color: rgb(0, 85, 255);")
        self.start_button.setObjectName("start_button")
        self.input_label = QtWidgets.QLabel(self.centralwidget)
        self.input_label.setGeometry(QtCore.QRect(20, 220, 191, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_label.setFont(font)
        self.input_label.setObjectName("input_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lectura de Sensor"))
        self.students_label.setText(_translate("MainWindow", "Cristian Villamil\n"
"David Rodriguez\n"
"Laura Valiente\n"
"Johant Piracoca"))
        self.measurement_label.setText(_translate("MainWindow", "TextLabel"))
        self.start_button.setText(_translate("MainWindow", "INICIAR LECTURA"))
        self.input_label.setText(_translate("MainWindow", "Tiempo de medición (s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
