# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(420, 30, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setPlaceholderText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 100, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 210, 300, 300))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 200, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 270, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


#*****************************************************************
        self.option = 0
        self.comboBox.currentIndexChanged.connect(self.set_option)
        self.label_2.setPixmap(QtGui.QPixmap("robot_cartesiano.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_3.setPixmap(QtGui.QPixmap("logo_ecci2.png"))
        self.label_3.setScaledContents(True)

        
    def set_option(self, currentIndex):
        self.option = currentIndex


        if(self.option == 0):
            robot_type = "cartesíano"
            # print("Robot Cartesiano")
            articulaciones = "3 articulaciones prismáticas"
            image = "robot_cartesiano.jpeg"
        

        elif(self.option == 1):
            robot_type = "cilíndrico"
            # print("Robot Cilíndrico")
            articulaciones = "1 articulación rotacional y 2 prismáticas"    
            image = "robot_cilindrico.png"
            self.label_2.setPixmap(QtGui.QPixmap("./robot_cilindrico.png"))
            self.label_2.setScaledContents(True)


        elif(self.option == 2):
            robot_type = "esférico"
            # print("Robot Esférico")
            articulaciones = "2 articulaciones rotacionales y 1 prismática"
            image = "robot_esferico.png"
            self.label_2.setPixmap(QtGui.QPixmap("./robot_esferico.png"))
            self.label_2.setScaledContents(True)


        mesaje = f'El robot {robot_type} consta de {articulaciones}'
        self.label.setText(mesaje)
        self.label_2.setPixmap(QtGui.QPixmap(image))
        self.label_2.setScaledContents(True)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Selector de Robots"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Cartesiano"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cilíndrico"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Esférico"))
        self.label.setText(_translate("MainWindow", "Elija un tipo de robot para visualizar sus caracteristicas"))
        self.label_4.setText(_translate("MainWindow", "Cristian Villamil\n"
"David Rodriguez\n"
"Johant Piracoca\n"
"Laura Valiente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
