# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Taller2_11.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math

class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(673, 573)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(30, 10, 201, 61))
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(300, 130, 101, 31))
                self.label_2.setObjectName("label_2")
                self.Resultado_2 = QtWidgets.QLabel(self.centralwidget)
                self.Resultado_2.setGeometry(QtCore.QRect(210, 470, 91, 21))
                self.Resultado_2.setText("")
                self.Resultado_2.setObjectName("Resultado_2")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(110, 310, 81, 21))
                self.label_4.setObjectName("label_4")
                self.Valor_1 = QtWidgets.QTextEdit(self.centralwidget)
                self.Valor_1.setGeometry(QtCore.QRect(200, 220, 111, 31))
                self.Valor_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
                self.Valor_1.setObjectName("Valor_1")
                self.Valor_2 = QtWidgets.QTextEdit(self.centralwidget)
                self.Valor_2.setGeometry(QtCore.QRect(200, 260, 111, 31))
                self.Valor_2.setObjectName("Valor_2")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(430, 0, 211, 131))
                self.label_5.setStyleSheet("border-image: url(logo1.png);")
                self.label_5.setText("")
                self.label_5.setObjectName("label_5")
                self.Residuo = QtWidgets.QPushButton(self.centralwidget)
                self.Residuo.setGeometry(QtCore.QRect(400, 280, 75, 23))
                self.Residuo.setObjectName("Residuo")
                self.Division = QtWidgets.QPushButton(self.centralwidget)
                self.Division.setGeometry(QtCore.QRect(500, 250, 75, 23))
                self.Division.setObjectName("Division")
                self.Multiplicacion = QtWidgets.QPushButton(self.centralwidget)
                self.Multiplicacion.setGeometry(QtCore.QRect(400, 250, 75, 23))
                self.Multiplicacion.setObjectName("Multiplicacion")
                self.Resta = QtWidgets.QPushButton(self.centralwidget)
                self.Resta.setGeometry(QtCore.QRect(500, 220, 75, 23))
                self.Resta.setObjectName("Resta")
                self.Suma = QtWidgets.QPushButton(self.centralwidget)
                self.Suma.setGeometry(QtCore.QRect(400, 220, 75, 23))
                self.Suma.setObjectName("Suma")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(250, 170, 191, 31))
                self.label_6.setAlignment(QtCore.Qt.AlignCenter)
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(250, 360, 191, 31))
                self.label_7.setAlignment(QtCore.Qt.AlignCenter)
                self.label_7.setObjectName("label_7")
                self.Seno = QtWidgets.QPushButton(self.centralwidget)
                self.Seno.setGeometry(QtCore.QRect(400, 410, 75, 23))
                self.Seno.setObjectName("Seno")
                self.Coseno = QtWidgets.QPushButton(self.centralwidget)
                self.Coseno.setGeometry(QtCore.QRect(400, 470, 75, 23))
                self.Coseno.setObjectName("Coseno")
                self.Tangente = QtWidgets.QPushButton(self.centralwidget)
                self.Tangente.setGeometry(QtCore.QRect(400, 440, 75, 23))
                self.Tangente.setObjectName("Tangente")
                self.Cotangente = QtWidgets.QPushButton(self.centralwidget)
                self.Cotangente.setGeometry(QtCore.QRect(500, 440, 75, 23))
                self.Cotangente.setObjectName("Cotangente")
                self.Cosecante = QtWidgets.QPushButton(self.centralwidget)
                self.Cosecante.setGeometry(QtCore.QRect(500, 410, 75, 23))
                self.Cosecante.setObjectName("Cosecante")
                self.Secante = QtWidgets.QPushButton(self.centralwidget)
                self.Secante.setGeometry(QtCore.QRect(500, 470, 75, 23))
                self.Secante.setObjectName("Secante")
                self.Valor_3 = QtWidgets.QTextEdit(self.centralwidget)
                self.Valor_3.setGeometry(QtCore.QRect(200, 420, 111, 31))
                self.Valor_3.setObjectName("Valor_3")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(110, 470, 81, 21))
                self.label_8.setObjectName("label_8")
                self.Resultado = QtWidgets.QLabel(self.centralwidget)
                self.Resultado.setGeometry(QtCore.QRect(210, 310, 91, 21))
                self.Resultado.setText("")
                self.Resultado.setObjectName("Resultado")
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(90, 230, 91, 21))
                self.label_10.setAlignment(QtCore.Qt.AlignCenter)
                self.label_10.setObjectName("label_10")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(90, 270, 91, 21))
                self.label_11.setAlignment(QtCore.Qt.AlignCenter)
                self.label_11.setObjectName("label_11")
                self.label_12 = QtWidgets.QLabel(self.centralwidget)
                self.label_12.setGeometry(QtCore.QRect(90, 430, 91, 21))
                self.label_12.setAlignment(QtCore.Qt.AlignCenter)
                self.label_12.setObjectName("label_12")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(30, 30, 201, 61))
                self.label_3.setAlignment(QtCore.Qt.AlignCenter)
                self.label_3.setObjectName("label_3")
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(30, 50, 201, 61))
                self.label_9.setAlignment(QtCore.Qt.AlignCenter)
                self.label_9.setObjectName("label_9")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(30, 90, 201, 61))
                self.label_13.setAlignment(QtCore.Qt.AlignCenter)
                self.label_13.setObjectName("label_13")
                self.label_14 = QtWidgets.QLabel(self.centralwidget)
                self.label_14.setGeometry(QtCore.QRect(280, 70, 81, 31))
                self.label_14.setAlignment(QtCore.Qt.AlignCenter)
                self.label_14.setObjectName("label_14")
                self.label_15 = QtWidgets.QLabel(self.centralwidget)
                self.label_15.setGeometry(QtCore.QRect(250, 50, 151, 31))
                self.label_15.setAlignment(QtCore.Qt.AlignCenter)
                self.label_15.setObjectName("label_15")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                self.Suma.clicked.connect(self.sumar)
                self.Resta.clicked.connect(self.restar)
                self.Multiplicacion.clicked.connect(self.multiplicacion)
                self.Division.clicked.connect(self.division)
                self.Residuo.clicked.connect(self.residuo)
                self.Seno.clicked.connect(self.seno)
                self.Coseno.clicked.connect(self.coseno)
                self.Tangente.clicked.connect(self.tangente)
                self.Cotangente.clicked.connect(self.cotangente)
                self.Cosecante.clicked.connect(self.cosecante)
                self.Secante.clicked.connect(self.secante)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Laura V Valiente</span></p></body></html>"))
                self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Calculadora</span></p></body></html>"))
                self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Resultado:</span></p></body></html>"))
                self.Valor_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
                self.Valor_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
                self.Residuo.setText(_translate("MainWindow", "Residuo"))
                self.Division.setText(_translate("MainWindow", "Division"))
                self.Multiplicacion.setText(_translate("MainWindow", "Multiplicacion"))
                self.Resta.setText(_translate("MainWindow", "Resta"))
                self.Suma.setText(_translate("MainWindow", "Suma"))
                self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Aritmeticas</span></p></body></html>"))
                self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Trigonometricas</span></p></body></html>"))
                self.Seno.setText(_translate("MainWindow", "Seno"))
                self.Coseno.setText(_translate("MainWindow", "Coseno"))
                self.Tangente.setText(_translate("MainWindow", "Tangente"))
                self.Cotangente.setText(_translate("MainWindow", "Cotangente"))
                self.Cosecante.setText(_translate("MainWindow", "Cosecante"))
                self.Secante.setText(_translate("MainWindow", "Secante"))
                self.Valor_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
                self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Resultado:</span></p></body></html>"))
                self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Valor 1:</span></p></body></html>"))
                self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Valor 2:</span></p></body></html>"))
                self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Valor 3:</span></p><p><br/></p></body></html>"))
                self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">David A Rodriguez</span></p></body></html>"))
                self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Nicolas D Villamil</span></p></body></html>"))
                self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Camilo Piracoca</span></p><p><br/></p></body></html>"))
                self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">2024</span></p></body></html>"))
                self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">EP Algoritmos Robotica</span></p></body></html>"))
        
        def sumar(self):
                a = self.Valor_1.toPlainText()
                b = self.Valor_2.toPlainText()
                c = float(a) + float(b)
                self.Resultado.setText(str(c))

        def restar(self):
                a = self.Valor_1.toPlainText()
                b = self.Valor_2.toPlainText()
                c = float(a) - float(b)
                self.Resultado.setText(str(c))

        def multiplicacion(self):
                a = self.Valor_1.toPlainText()
                b = self.Valor_2.toPlainText()
                c = float(a)*float(b)
                self.Resultado.setText(str(c))


        def division(self):
                try:
                        a = self.Valor_1.toPlainText()
                        b = self.Valor_2.toPlainText()
                        if b==0:
                                raise ValueError("El límite inferior debe ser menor que el límite superior.")
                except ValueError:
                                c = float(a) / float(b)
                                self.Resultado.setText(str(c))
                        

        def residuo(self):
                try:
                        a = self.Valor_1.toPlainText()
                        b = self.Valor_2.toPlainText()
                        if b==0:
                                raise ValueError("El límite inferior debe ser menor que el límite superior.")
                except ValueError:
                                c = float(a) % float(b)
                                self.Resultado.setText(str(c))


        def seno(self):
                a = float(self.Valor_3.toPlainText())
                radianes = a* (math.pi / 180)  
                c = math.sin(radianes)
                self.Resultado_2.setText(str(c))

        def coseno(self):
                a = float(self.Valor_3.toPlainText())
                radianes = a* (math.pi / 180)  
                c = math.cos(radianes)
                self.Resultado_2.setText(str(c))

        def tangente(self):
                a = float(self.Valor_3.toPlainText())
                radianes = a* (math.pi / 180)  
                c = math.tan(radianes)
                self.Resultado_2.setText(str(c))

        def cotangente(self):
                a = float(self.Valor_3.toPlainText())
                radianes = a* (math.pi / 180)  
                c = (1/(math.tan(radianes)))
                self.Resultado_2.setText(str(c))

        def secante(self):
                a = float(self.Valor_3.toPlainText())
                radianes = a* (math.pi / 180)  
                c = (1/(math.cos(radianes)))
                self.Resultado_2.setText(str(c))

        def cosecante(self):
                a = float(self.Valor_3.toPlainText())
                radianes = a* (math.pi / 180)  
                c = (1/(math.sin(radianes)))
                self.Resultado_2.setText(str(c))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
